### ISSUE TITLE
https blocked content

### ISSUE THREAD

**Issue by spawn81** [junkboy0315/vue-responsive-youtube#1]
Hi,
first of all I would to thank you for your component.
Just one thing, you should update the youtube link adding ssl, otherwise the content will be blocked if a website is under ssl.
just edit
`return `http://www.youtube.com/embed/${this.videoId}`;`
adding an s
`return `https://www.youtube.com/embed/${this.videoId}`;`

bye

**Comment by tam315** [comment]
@spawn81 
Thanks! I'll fix it.
